apiVersion: awi.cisco.awi/v1
kind: InterNetworkDomainConnection # Connection across network domains
metadata:
  name: "AWI staging to development"       #generate an appropriate name
spec:
  source:
    metadata:
      name: "AWI staging environment" #source network domain name
      description: ""
    networkDomain:
      selector: #Select network name based on the below selection criteria
        matchId:
          id: "vpc-0fe7d06b468142a7e"
  destination:
    metadata:
      name: "AWI development environment" #Destination network domain name
      description: ""
    networkDomain:
      selector: #Select network name based on the below selection criteria
        matchId:
          id: "vpc-0fe7d06b468142a7e"
